# Generated by Django 5.0.6 on 2024-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Verses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("speaker", models.CharField(max_length=100)),
                ("context", models.TextField()),
                (
                    "book",
                    models.CharField(
                        choices=[
                            ("SI", "The Silmarillion"),
                            ("HO", "The Hobbit"),
                            ("FR", "The Fellowship of the Ring"),
                            ("TO", "The Two Towers"),
                            ("RK", "The Return of the King"),
                            ("UT", "Unfinished Tales"),
                            ("CH", "The Children of Hurin"),
                            ("BL", "Beren and Luthien"),
                            ("FG", "The Fall of Gondolin"),
                            ("FN", "The Fall of Numenor"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sub_book", models.CharField(blank=True, max_length=20, null=True)),
                ("chapter", models.CharField(blank=True, max_length=10, null=True)),
                ("page", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
