# Generated by Django 5.0.6 on 2024-09-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Characters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("aka", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("Human", "Human"),
                            ("Elf", "Elf"),
                            ("Dwarf", "Dwarf"),
                            ("Hobbit", "Hobbit"),
                            ("Valar", "Valar"),
                            ("Maiar", "Maiar"),
                            ("Orc", "Orc"),
                            ("Uruk-Hai", "Uruk-Hai"),
                            ("Goblin", "Goblin"),
                            ("Eagle", "Eagle"),
                            ("Spider", "Spider"),
                            ("Troll", "Troll"),
                            ("Ent", "Ent"),
                            ("Balrog", "Balrog"),
                            ("Dragon", "Dragon"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Characters",
            },
        ),
        migrations.CreateModel(
            name="Verses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("context", models.TextField()),
                (
                    "book",
                    models.CharField(
                        choices=[
                            ("SI", "The Silmarillion"),
                            ("HO", "The Hobbit"),
                            ("FR", "The Fellowship of the Ring"),
                            ("TO", "The Two Towers"),
                            ("RK", "The Return of the King"),
                            ("UT", "Unfinished Tales"),
                            ("CH", "The Children of Hurin"),
                            ("BL", "Beren and Luthien"),
                            ("FG", "The Fall of Gondolin"),
                            ("FN", "The Fall of Numenor"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sub_book", models.CharField(blank=True, max_length=20, null=True)),
                ("chapter", models.CharField(blank=True, max_length=10, null=True)),
                ("page", models.CharField(blank=True, max_length=10, null=True)),
                ("speaker", models.ManyToManyField(to="middle_earth.characters")),
            ],
            options={
                "verbose_name_plural": "Verses",
            },
        ),
    ]
