# Generated by Django 5.0.6 on 2024-09-07 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verses",
            options={"verbose_name_plural": "Verses"},
        ),
    ]
