# Generated by Django 5.0.6 on 2024-09-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characters",
            name="race",
            field=models.CharField(
                choices=[
                    ("Human", "Human"),
                    ("Elf", "Elf"),
                    ("Dwarf", "Dwarf"),
                    ("Hobbit", "Hobbit"),
                    ("Valar", "Valar"),
                    ("Maiar", "Maiar"),
                    ("Orc", "Orc"),
                    ("Uruk-Hai", "Uruk-Hai"),
                    ("Goblin", "Goblin"),
                    ("Eagle", "Eagle"),
                    ("Spider", "Spider"),
                    ("Troll", "Troll"),
                    ("Ent", "Ent"),
                    ("Balrog", "Balrog"),
                    ("Dragon", "Dragon"),
                    ("Wight", "Wight"),
                    ("Other/Unknown", "Other/Unknown"),
                ],
                max_length=100,
            ),
        ),
    ]
