# Generated by Django 5.0.6 on 2024-09-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verses",
            name="speaker",
        ),
        migrations.AddField(
            model_name="verses",
            name="speaker",
            field=models.ManyToManyField(to="middle_earth.characters"),
        ),
    ]
