# Generated by Django 5.0.6 on 2024-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0002_alter_characters_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="picture",
            field=models.ImageField(blank=True, upload_to="character_pictures/"),
        ),
    ]
