# Generated by Django 5.0.6 on 2024-09-08 01:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0003_characters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characters",
            options={"verbose_name_plural": "Characters"},
        ),
    ]
