# Generated by Django 5.0.6 on 2024-09-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0003_characters_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="picture_credit",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
