# Generated by Django 5.0.6 on 2024-09-09 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0004_characters_picture_credit"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Characters",
            new_name="Character",
        ),
        migrations.RenameModel(
            old_name="Verses",
            new_name="Verse",
        ),
    ]
