# Generated by Django 5.0.6 on 2024-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0005_rename_characters_character_rename_verses_verse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sub_continent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Beleriand", "Beleriand"),
                            (
                                "Middle Earth at End of Third Age",
                                "Middle Earth at End of Third Age",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
