# Generated by Django 5.0.6 on 2024-09-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0006_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("picture", models.ImageField(blank=True, upload_to="thing_pictures/")),
                (
                    "picture_credit",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="picture",
            field=models.ImageField(blank=True, upload_to="place_pictures/"),
        ),
        migrations.AddField(
            model_name="place",
            name="picture_credit",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
