# Generated by Django 5.0.6 on 2024-09-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0007_thing_place_picture_place_picture_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="aka",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="AKA"
            ),
        ),
    ]
